var categories = [
  [1, "Animals", "Domestic"],
  [2, "Animals", "Human"],
  [3, "Animals", "Pet"],
  [4, "Animals", "Spawner"],
  [5, "Animals", "Wildlife"],
  [6, "Areas", "Creator"],
  [7, "Areas", "Modifier"],
  [8, "Areas", "Random"],
  [9, "Areas", "Surface"],
  [10, "Buildings", "Commercial High"],
  [11, "Buildings", "Commercial Low"],
  [12, "Buildings", "Industrial Manufacturing"],
  [13, "Buildings", "Industrial Warehouse"],
  [14, "Buildings", "Office High"],
  [15, "Buildings", "Office Low"],
  [16, "Buildings", "Residential High"],
  [17, "Buildings", "Residential Low"],
  [18, "Buildings", "Residential Medium"],
  [19, "Buildings", "Residential Mixed"],
  [20, "Buildings", "Residential Rowhouse"],
  [21, "Buildings", "Specialized Industry"],
  [22, "Buildings", "Specialized Industry Base"],
  [23, "Communications", "Internet"],
  [24, "Communications", "Post"],
  [25, "Editor Elements", "Container"],
  [26, "Editor Elements", "Outside Connection"],
  [27, "Editor Elements", "Tiles"],
  [28, "Editor Elements", "Transportation"],
  [29, "Editor Elements", "Water Source"],
  [30, "Education & Research", "Education"],
  [31, "Education & Research", "Research"],
  [32, "Effects", "Audio Randomize"],
  [33, "Effects", "Audio Spot"],
  [34, "Effects", "Lights"],
  [35, "Effects", "SFX"],
  [36, "Effects", "VFX"],
  [37, "Electricity", "Battery"],
  [38, "Electricity", "Power Plant"],
  [39, "Electricity", "Power Plant Base"],
  [40, "Electricity", "Renewable"],
  [41, "Electricity", "Transformer"],
  [42, "Fire and Rescue", "Disaster Control"],
  [43, "Fire and Rescue", "Firefighting"],
  [44, "Garbage", "Storage"],
  [45, "Garbage", "Processor"],
  [46, "Landscaping", "Bushes"],
  [47, "Landscaping", "Random"],
  [48, "Landscaping", "Trees"],
  [49, "Medical", "Deathcare"],
  [50, "Medical", "Healthcare"],
  [51, "Networks", "Highway Bridge"],
  [52, "Networks", "Highways"],
  [53, "Networks", "Intersections"],
  [54, "Networks", "Invisible"],
  [55, "Networks", "Large Bridge"],
  [56, "Networks", "Large Roads"],
  [57, "Networks", "Medium Bridge"],
  [58, "Networks", "Medium Roads"],
  [59, "Networks", "Path"],
  [60, "Networks", "Pedestrian Bridge"],
  [61, "Networks", "Pipes"],
  [62, "Networks", "Power Line"],
  [63, "Networks", "Public Transport"],
  [64, "Networks", "Seaways"],
  [65, "Networks", "Small Bridge"],
  [66, "Networks", "Small Roads"],
  [67, "Parks & Recreation", "Basic Parks"],
  [68, "Parks & Recreation", "Landmark"],
  [69, "Parks & Recreation", "Large Parks"],
  [70, "Parks & Recreation", "Large Sports Park"],
  [71, "Parks & Recreation", "Maintenance"],
  [72, "Parks & Recreation", "Sports Park"],
  [73, "Parks & Recreation", "Tourist Attractions"],
  [74, "Police & Administration", "Administration"],
  [75, "Police & Administration", "Police"],
  [76, "Props", "Miscellaneous"],
  [77, "Props", "Ads"],
  [78, "Props", "Commercial"],
  [79, "Props", "Decals"],
  [80, "Props", "Decoration"],
  [81, "Props", "Fire Hydrant"],
  [82, "Props", "Industrial"],
  [83, "Props", "Lights"],
  [84, "Props", "Pillar"],
  [85, "Props", "Random"],
  [86, "Props", "Recreational"],
  [87, "Props", "Residential"],
  [88, "Props", "Rocks"],
  [89, "Props", "Storefront"],
  [90, "Props", "Street Signs"],
  [91, "Props", "Traffic Lights"],
  [92, "Road Service", "Maintenance"],
  [93, "Road Service", "Parking"],
  [94, "Road Service", "Roundabouts"],
  [95, "Road Service", "Traffic Control"],
  [96, "Road Service", "Upgrades"],
  [97, "Signature Buildings", "Commercial"],
  [98, "Signature Buildings", "Industrial"],
  [99, "Signature Buildings", "Mixed Residential"],
  [100, "Signature Buildings", "Office"],
  [101, "Signature Buildings", "Residential"],
  [102, "Sub Buildings", "Dummy Buildings"],
  [103, "Sub Buildings", "Internal Upgrade"],
  [104, "Sub Buildings", "Specialized Industry Dummy"],
  [105, "Transportation", "Air Service"],
  [106, "Transportation", "Bus Service"],
  [107, "Transportation", "Subway Service"],
  [108, "Transportation", "Taxi Service"],
  [109, "Transportation", "Train Service"],
  [110, "Transportation", "Tram Service"],
  [111, "Transportation", "Water Service"],
  [112, "Uncategorized", "Delivery Piles"],
  [113, "Uncategorized", "Industrial"],
  [114, "Uncategorized", "Location"],
  [115, "Uncategorized", "Marker"],
  [116, "Uncategorized", "Networks"],
  [117, "Uncategorized", "Props"],
  [118, "Uncategorized", "Spawn Location"],
  [119, "Uncategorized", "Specialized Industry Placeholder"],
  [120, "Uncategorized", "Takeoff"],
  [121, "Uncategorized", "Transportation"],
  [122, "Uncategorized", "Utility"],
  [123, "Vehicles", "Administration"],
  [124, "Vehicles", "Ambulance"],
  [125, "Vehicles", "Bus"],
  [126, "Vehicles", "Cargo Airplane"],
  [127, "Vehicles", "Delivery Vehicle"],
  [128, "Vehicles", "Fire Truck"],
  [129, "Vehicles", "Garbage"],
  [130, "Vehicles", "Hearse"],
  [131, "Vehicles", "Helicopter"],
  [132, "Vehicles", "Industrial Machinery"],
  [133, "Vehicles", "Maintenance"],
  [134, "Vehicles", "Passenger Airplane"],
  [135, "Vehicles", "Police"],
  [136, "Vehicles", "Post"],
  [137, "Vehicles", "Private Vehicle"],
  [138, "Vehicles", "Ship"],
  [139, "Vehicles", "Spaceship"],
  [140, "Vehicles", "Subway"],
  [141, "Vehicles", "Taxi"],
  [142, "Vehicles", "Trailer"],
  [143, "Vehicles", "Train"],
  [144, "Vehicles", "Tram"],
  [145, "Water & Sewage", "Sewage Processing"],
  [146, "Water & Sewage", "Water Pump"],
];
